"""Add extra fields to Voter model

Revision ID: 32c49431c55e
Revises: 6f64c07d54cc
Create Date: 2025-08-20 00:30:49.176076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32c49431c55e'
down_revision = '6f64c07d54cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audience', sa.String(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('author')
        batch_op.drop_column('message')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mobile Number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Education Level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Political Affiliation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Key Issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Remarks', sa.Text(), nullable=True))
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('political_affiliation')
        batch_op.drop_column('occupation')
        batch_op.drop_column('key_issues')
        batch_op.drop_column('notes')
        batch_op.drop_column('education')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('key_issues', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('political_affiliation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('Remarks')
        batch_op.drop_column('Key Issues')
        batch_op.drop_column('Political Affiliation')
        batch_op.drop_column('Education Level')
        batch_op.drop_column('Occupation')
        batch_op.drop_column('Mobile Number')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('audience')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
