"""Add worker module features

Revision ID: 6f64c07d54cc
Revises: 552335b026fd
Create Date: 2025-08-19 21:03:46.593177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f64c07d54cc'
down_revision = '552335b026fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))
        batch_op.drop_column('audience')
        batch_op.drop_column('body')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('political_affiliation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('key_issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('key_issues')
        batch_op.drop_column('political_affiliation')
        batch_op.drop_column('education')
        batch_op.drop_column('occupation')
        batch_op.drop_column('mobile_number')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('audience', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('author')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
