"""Add candidate models and booth/segment tables

Revision ID: 7c0ca5f63461
Revises: 32c49431c55e
Create Date: 2025-08-23 14:23:25.405448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c0ca5f63461'
down_revision = '32c49431c55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('booth_number', sa.String(length=50), nullable=True),
    sa.Column('in_charge_name', sa.String(length=255), nullable=True),
    sa.Column('in_charge_contact', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booth_number')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('booth_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'booths', ['booth_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booth_id')
        batch_op.drop_column('has_voted')

    op.drop_table('segments')
    op.drop_table('booths')
    # ### end Alembic commands ###
